# Base template for RHEL-family distributions
# Usage: FROM <base_image>
# Variables: BASE_IMAGE, PACKAGE_MANAGER, PACKAGES

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Install systemd and essential packages
RUN ${PACKAGE_MANAGER} update -y && \
    ${PACKAGE_MANAGER} install -y \
        systemd \
        python3 \
        python3-pip \
        sudo \
        bash \
        vim \
        iproute \
        procps-ng \
        ${EXTRA_PACKAGES} && \
    ${PACKAGE_MANAGER} clean all

# Create ansible user
RUN useradd -m -s /bin/bash ansible && \
    echo 'ansible ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ansible

# Configure systemd
RUN systemctl set-default multi-user.target && \
    systemctl mask dev-hugepages.mount sys-fs-fuse-connections.mount

# Set working directory
WORKDIR /

# Default command
CMD ["/usr/sbin/init"]